### ISSUE TITLE
Why Github links to this repository for pygame dependencies?

### ISSUE THREAD

**Issue by PatMyron** [dskeba/pygame#5]
Examples:
https://github.com/PatMyron/super-mario-pygame/network/dependencies

https://github.com/mfurga/chip8/network/dependencies
https://github.com/SebDeclercq/OC_Projet_3/network/dependencies

**Comment by MattIPv4** [comment]
This appears to be because setup.py declares this as the pygame package which is incorrect...

**Comment by PatMyron** [comment]
```
Yes, you're correct and we're aware of the issue. The packages are algorithmically determined but can manually remap them as I have now done for the pygame package.

Thanks for taking the time to let us know.

Let us know if there's anything else we can do for you.

Cheers,
GitHub Support
```
